### ISSUE TITLE
Raising the accuracy

### ISSUE THREAD

**Issue by SylviaPscheidl** [GrHalbgott/Fossgis22_Plants-vs-CO2#4]
Like you said, the values are estimated and not scientifically proven. But there could be a way to raise the accuracy of the result.
For areas with a latitude like for example Germany, the vegetation underlies huge transitions between the seasons. According to from which season your chosen satellite picture came from, the results vary strongly because you assume that the vegetation conditions are like this the whole year. It`s hard to make a solid statement about the emission absorption because you combine one value for the whole year (CO2 emission) and one snapshot (NDWI of a the chosen season). 

One way to reduce this problem could be to lower the study period. One possibility is to split the CO2 value into four parts, for four seasons and concentrate on the season the satellite picture was taken.  We can keep in mind that also the CO2 emissions vary during the year, but not as massive as the absorption ability of the vegetation.

**Comment by GrHalbgott** [comment]
That is quite a good idea, thank you very much! We already thought about using another source of emission data (raster) to achieve a higher accuracy of the values, but that needs much more work and your idea seems like a faster approach. Your idea will definitely be included in the report if we don't have enough time to already include it in the model.
